version: '3'
services:
  strapi:
    image: strapi/strapi:latest
    volumes:
      - ./strapi-project-app:/usr/src/api
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: root
    ports:
      - '1337:1337'
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: strapi_db

  prometheus:
      image: prom/prometheus
      volumes:
         - D:/CFA-INSTA-COURS/CODE/DEVOPSCRV/prometheus-2.49.1:/etc/prometheus
        #- ./prometheus:/etc/prometheus
      ports:
        - '9092:9090'

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - '3001:3000'
    depends_on:
      - prometheus